#!/usr/bin/env python3
"""Generate native string tables from the reviewed, parallel UTF-8 catalog.

UI-only aliases cover capitalization and terminal ellipses. Storage keys,
font metadata and user text are never rewritten. Run with --check in CI.
"""
from pathlib import Path
import json
import re
import sys

ROOT = Path(__file__).resolve().parents[2]
LANGUAGES = ['en', 'fr', 'es', 'de', 'ja', 'hi', 'zh-Hans', 'zh-Hant', 'pt-BR', 'it', 'ko']

def normalize(value):
    return value.rstrip('…').casefold()

def tables():
    rows = {}
    for number, line in enumerate((ROOT / 'scripts/localization/catalog.tsv').read_text().splitlines(), 1):
        if not line or line.startswith('#'):
            continue
        values = [v.replace('\\n', '\n') for v in line.split('|')]
        if len(values) != len(LANGUAGES) or any(not v.strip() for v in values):
            raise ValueError(f'Incomplete translation row {number}: {len(values)} columns')
        if values[0] in rows:
            raise ValueError(f'Duplicate key on row {number}: {values[0]}')
        # All formatting arguments must remain intact; positional ordering is allowed.
        def placeholders(value):
            return sorted(re.findall(r'%(?:\d+\$)?(?:lld|ld|d|@)', value.replace('%%', '')))
        expected = sorted(re.sub(r'\d+\$', '', v) for v in placeholders(values[0]))
        for value in values[1:]:
            if sorted(re.sub(r'\d+\$', '', v) for v in placeholders(value)) != expected:
                raise ValueError(f'Placeholder mismatch on row {number}: {value}')
        rows[values[0]] = values
    aliases = {normalize(k): v for k, v in rows.items()}
    for source in (ROOT / 'Sources').glob('*.swift'):
        if 'Checks' in source.name:
            continue
        for match in re.finditer(r'"((?:[^"\\]|\\.)*)"', source.read_text()):
            raw = match[1]
            if '\\(' in raw:
                continue
            try:
                key = json.loads('"' + raw + '"')
            except ValueError:
                continue
            canonical = aliases.get(normalize(key))
            if canonical and key not in rows:
                suffix = '…' if key.endswith('…') else ''
                rows[key] = [key] + [v.rstrip('…') + suffix for v in canonical[1:]]
    return rows

def main():
    rows = tables()
    check = '--check' in sys.argv
    for index, language in enumerate(LANGUAGES):
        path = ROOT / 'Sources/Localizations' / f'{language}.lproj/Localizable.strings'
        content = '// Generated by scripts/localization/generate.py; edit catalog.tsv.\n'
        content += '\n'.join(f'{json.dumps(key, ensure_ascii=False)} = {json.dumps(row[index], ensure_ascii=False)};' for key, row in sorted(rows.items())) + '\n'
        if check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f'Stale localization: {path.relative_to(ROOT)}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    print(f'Localization tables: {len(rows)} keys × {len(LANGUAGES)} languages; complete columns and format arguments verified.')

if __name__ == '__main__':
    main()
