#!/usr/bin/env python3
"""Fit a small local width prior; never load a benchmark's hidden outlines."""
import argparse
import hashlib
import json
from pathlib import Path

import numpy as np

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--dataset', type=Path, required=True)
parser.add_argument('--output', type=Path, required=True)
parser.add_argument('--swift-constants', type=Path)
args = parser.parse_args()
source = args.dataset.read_bytes()
dataset = json.loads(source)
references = list('HOnop')
targets = [c for c in 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz' if c not in references]
if dataset.get('schemaVersion') != 1 or dataset.get('references') != references or dataset.get('targets') != targets:
    raise ValueError('Unexpected width-dataset schema or character ordering')
records = dataset['records']
features = np.asarray([r['features'] for r in records], dtype=np.float64)
ratios = np.asarray([r['logWidthRatios'] for r in records], dtype=np.float64)
if features.shape != (len(records), 8) or ratios.shape != (len(records), 47):
    raise ValueError('Expected eight source features and 47 target width ratios per face')
if not np.isfinite(features).all() or not np.isfinite(ratios).all():
    raise ValueError('Non-finite training measurements')
validation = np.asarray([int(hashlib.sha256(r['family'].encode()).hexdigest()[:8], 16) % 5 == 0 for r in records])
train = ~validation
train_families = {r['family'] for r, selected in zip(records, train) if selected}
validation_families = {r['family'] for r, selected in zip(records, validation) if selected}
if len(records) < 50 or len(train_families) < 2 or len(validation_families) < 2:
    raise ValueError('Too few distinct families for the fixed family-level split')
means = features[train].mean(axis=0)
scales = np.maximum(features[train].std(axis=0), 0.03)
design = np.column_stack([np.ones(len(records)), (features-means)/scales])
trials = []
for ridge in (0.1, 1.0, 10.0, 100.0):
    penalty = np.eye(design.shape[1])*ridge
    penalty[0, 0] = 0
    weights = np.linalg.solve(design[train].T@design[train]+penalty, design[train].T@ratios[train])
    error = float(np.mean((design[validation]@weights-ratios[validation])**2))
    trials.append((error, ridge))
    print(f'Family validation: ridge={ridge:g}, log-width MSE={error:.9f}')
error, ridge = min(trials)
penalty = np.eye(design.shape[1])*ridge
penalty[0, 0] = 0
# Hyperparameters and normalization are frozen before the full-corpus refit.
weights = np.linalg.solve(design.T@design+penalty, design.T@ratios)
if not np.isfinite(weights).all():
    raise ValueError('Non-finite fitted coefficients')
fingerprint = hashlib.sha256(source).hexdigest()
model = {
    'schemaVersion': 1, 'characters': targets, 'references': references,
    'mean': means.tolist(), 'std': scales.tolist(), 'degree': 1,
    'ridge': ridge, 'weights': weights.tolist(), 'maximumStandardizedFeature': 4,
    'datasetSHA256': fingerprint, 'faceCount': len(records),
    'familyCount': len(train_families|validation_families),
    'selectionTrainFaceCount': int(train.sum()), 'validationFaceCount': int(validation.sum()),
    'validationFamilyCount': len(validation_families), 'validationLogWidthMSE': error,
}
args.output.write_text(json.dumps(model, indent=2, sort_keys=True)+'\n')
if args.swift_constants:
    def array(values):
        return '['+', '.join(format(float(v), '.12g') for v in values)+']'
    constants = [
        '// BEGIN GENERATED WIDTH PRIOR',
        '// Generated by scripts/starter-research/train-width-prior.py. Do not tune coefficients by hand.',
        f'// {len(records)} faces / {model["familyCount"]} families; input SHA-256 {fingerprint}.',
        f'    static let modelRevision = "width-v1-{fingerprint[:12]}"',
        '    private static let targetCharacters = Array("'+''.join(targets)+'").map(String.init)',
        '    private static let featureMeans: [Double] = '+array(means),
        '    private static let featureScales: [Double] = '+array(scales),
        '    private static let coefficients: [[Double]] = [',
    ]
    constants += ['        '+array(row)+', // '+c for c, row in zip(targets, weights.T)]
    constants += ['    ]', '// END GENERATED WIDTH PRIOR']
    args.swift_constants.write_text('\n'.join(constants)+'\n')
print(f'Frozen width prior: {len(records)} faces, {model["familyCount"]} families; {len(validation_families)} held-out families selected ridge {ridge:g}.')
